### ISSUE TITLE
Update `ondevice.io documentation > Installing ondevice > Mac OS`

### ISSUE THREAD

**Issue by evandrix** [ondevice/docs.ondevice.io#1]
$ ~brew install ondevice/tap/ondevice~
$ brew tap ondevice/ondevice && brew install ondevice

**Comment by mreithub** [comment]
Hi, thanks for reporting.

according to [How-to-Create-and-Maintain-a-Tap#installing][1], `users can install any of your formulae with brew install user/repo/formula. Homebrew will automatically add your github.com/user/homebrew-repo tap before installing the formula`. 

Could you elaborate on why you'd prefer the second command over the first one?

Or do you have trouble installing ondevice with the command mentioned in the documentation?

[1]: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#installing

**Comment by evandrix** [comment]
Yes, I have trouble installing `ondevice` with the command mentioned in the documentation.

**Comment by mreithub** [comment]
Just to follow up:
Do you still have the error message? Alternatively, could you provide some additional information on your setup? (MacOS version, etc.)
